apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgitops-app
  namespace: janus-argocd
spec:
  destination:
    namespace: kgitops
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: kafka
    repoURL: https://github.com/lordofthejars/kafka-gitops.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true